version: '3.8'

services:
  discordlm:
    build: .
    container_name: discordlm
    restart: unless-stopped
    
    # Mount your local characters directory
    volumes:
      - ./characters:/app/characters:ro  # Read-only mount for character files
      
    # Alternative: Mount from a different location
    # volumes:
    #   - /path/to/your/characters:/app/characters:ro
    
    # Environment variables - copy from .env file or set directly
    environment:
      # Required Discord settings
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_SELF_ID=${BOT_SELF_ID}
      
      # Required LLM settings  
      - OPENAI_URL=${OPENAI_URL}
      - OPENAI_KEY=${OPENAI_KEY}
      - MODEL_NAME=${MODEL_NAME}
      
      # Optional settings
      - TOKEN_LIMIT=${TOKEN_LIMIT:-32600}
      - ENABLE_AVATAR_SERVER=${ENABLE_AVATAR_SERVER:-false}
      - AVATAR_PORT=${AVATAR_PORT:-8080}
      - PUBLIC_AVATAR_BASE_URL=${PUBLIC_AVATAR_BASE_URL}
    
    # Expose avatar server port if enabled
    ports:
      - "${AVATAR_PORT:-8080}:${AVATAR_PORT:-8080}"
    
    # Use .env file if available
    env_file:
      - .env
    
    # Health check
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "discordlm"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# Alternative service for development with live reload
  discordlm-dev:
    image: denoland/deno
    container_name: discordlm-dev
    restart: unless-stopped
    working_dir: /app
    profiles: ["dev"]  # Only start with --profile dev
    
    volumes:
      - .:/app                           # Mount entire project for development
      - ./characters:/app/characters:ro  # Character files
    
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_SELF_ID=${BOT_SELF_ID}
      - OPENAI_URL=${OPENAI_URL}
      - OPENAI_KEY=${OPENAI_KEY}
      - MODEL_NAME=${MODEL_NAME}
      - TOKEN_LIMIT=${TOKEN_LIMIT:-32600}
      - ENABLE_AVATAR_SERVER=${ENABLE_AVATAR_SERVER:-false}
      - AVATAR_PORT=${AVATAR_PORT:-8080}
      - PUBLIC_AVATAR_BASE_URL=${PUBLIC_AVATAR_BASE_URL}
    
    ports:
      - "${AVATAR_PORT:-8080}:${AVATAR_PORT:-8080}"
    
    env_file:
      - .env
    
    command: ["deno", "task", "dev"]

